ScootsStats = {
    ['version'] = '2.7.2',
    ['frames'] = {
        ['event'] = CreateFrame('Frame', 'ScootsStatsEventFrame', UIParent),
        ['master'] = CreateFrame('Frame', 'ScootsStatsMasterFrame', _G['CharacterFrame']),
    },
    ['initialised'] = false,
    ['characterFrameOpen'] = false,
    ['optionsOpen'] = false,
    ['queuedUpdate'] = false,
    ['queuedAttunedUpdate'] = false,
    ['hookedTabs'] = false,
    ['firstOpen'] = true,
    ['prestiged'] = false,
    ['options'] = {
        ['mergedPrestige'] = false,
        ['fields'] = {
            ['misc'] = {
                ['attuning'] = true,
                ['attuninginv'] = true,
                ['movespeed'] = true,
            },
            ['base'] = {
                ['strength'] = true,
                ['agility'] = true,
                ['stamina'] = true,
                ['intellect'] = true,
                ['spirit'] = true,
            },
            ['melee'] = {
                ['damage'] = false,
                ['speed'] = false,
                ['power'] = false,
                ['hit'] = false,
                ['crit'] = false,
                ['expertise'] = false,
            },
            ['ranged'] = {
                ['damage'] = false,
                ['speed'] = false,
                ['power'] = false,
                ['hit'] = false,
                ['crit'] = false,
            },
            ['spells'] = {
                ['damage'] = false,
                ['healing'] = false,
                ['hit'] = false,
                ['crit'] = false,
                ['haste'] = false,
                ['regen'] = false,
            },
            ['defences'] = {
                ['armour'] = true,
                ['defense'] = true,
                ['dodge'] = true,
                ['parry'] = true,
                ['block'] = true,
                ['resilience'] = true,
            },
            ['prestige'] = {
                ['charattunes'] = true,
                ['accattunes'] = true,
                ['forgepower'] = true,
                ['lootcoercion'] = true,
                ['affixcoercion'] = true,
                ['bonusexp'] = true,
                ['luckyloot'] = true,
            },
        },
    },
}